### PR TITLE
Only prompt for variables within scope by fetching from deployments p…

### LINKED ISSUE #316: `release deploy` command does not respect Runbook or Environment scoping on Prompted variables
### Severity

Not blocking but is annoying when trying to deploy a release

### Version

Octopus Cloud 2024.1.6809 - Octopus GO CLI 2.1.0

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When trying to deploy a release using the new GO-based Octopus CLI it does not respect variable scoping (tested Environment and Process) and will prompt for the variable anyway.

`octopus release deploy --project NameofProject --environment Nameofenvironment --version Releasename --space Spacename`

See the reproduction for examples.

### Reproduction

1. Create a project with a runbook and a process step and make sure it can deploy to two environments.

2. Create a prompted variable and have it set to required. Ensure the variable is present in both the runbook and deployment process.

3. Scope the prompted variable to the runbook, create a release and go to deploy it via the Octopus UI, notice it does not ask for the prompted variable value.

image

image

4. Make sure you have the new GO-based CLI installed (latest version for my testing is 2.1.0) and run the command below to deploy that release:

`octopus release deploy --project NameofProject --environment Nameofenvironment --version Releasename --space Spacename`

ie 

`octopus release deploy --project OctopusCLIVariableTest --environment Test --version 0.0.8 --space Clare`

See the variable is prompted when it should not be:

image

5. To test the environment variable scoping change the prompted variable to be scoped to one environment:

image

Note for the deployment in the UI if selecting a different environment than the variable is scoped to it will not prompt for the variable:

image

But it will prompt for the environment the variable is scoped to:

image

6. Use the Go based CLI to deploy that release to the environment that the variable is NOT scoped to and see the variable is prompted even though it should not be:

image

### Error and Stacktrace

```shell
N/A
```

### More Information

Original ticket (internal) - https://octopus.zendesk.com/agent/tickets/167837
Slack discussion (internal) - https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1705058447596279

### Workaround

To workaround this issue you have three options:

- If you need to use the prompted variable in some deployments but not others and are required to use the command prompt then the .NET version of the CLI will work and will respect the variable scoping - https://octopus.com/docs/octopus-rest-api/octopus-cli.

- You can also use the UI to deploy if you are not required to use the command prompt.

- If you do not need the prompted variable you can use the `--no-prompt` flag with the new Go CLI which should work and no prompt for the variable ie: 

   `octopus release deploy --project OctopusCLIVariableTest --environment Test --version 0.0.8 --space Clare --no-prompt`

### PR DESCRIPTION
**Pull request by IsaacCalligeros95**
This adds support for only prompting on variables within the deployment scope using the deployments previews endpoint instead of the project variable set.

Currently fetch the variable set and prompt for all variables, regardless of the scope. The change to the CLI will only prompt for variables in that specific set of releases. This is handled by flattening the deployment previews, so if multiple environments contain differently scoped variables, they will all be prompted for and contributed. While they are all contributed due to variable scoping at deployment time the out of scope variables are not included in the manifest and therefore deployment. 

image

For this use case (showing prompted variables) tenant scoping is not allowed
image

When requesting a deployment previews for a tenant with environments out of scope those prompted variables are still returned. Tenant variables are also not able to be prompted. In the CLI consuming code this means specifying the tenant is redundant in our use case.
image

fixes #316 
Fixes https://github.com/OctopusDeploy/Issues/issues/8559

### CODE REVIEW

File: pkg/cmd/release/deploy/deploy.go [hunk 1]
```diff
@@ -562,7 +581,7 @@ func AskQuestions(octopus *octopusApiClient.Client, stdout io.Writer, asker ques
 
 		if !isExcludedStepsSpecified {
 			// select steps to exclude
-			deploymentProcess, err := deployments.GetDeploymentProcess(octopus, space.ID, selectedRelease.ProjectDeploymentProcessSnapshotID)
+			deploymentProcess, err := deployments.GetDeploymentProcessByID(octopus, space.ID, selectedRelease.ProjectDeploymentProcessSnapshotID)
```
Comment (IsaacCalligeros95) [inline pkg/cmd/release/deploy/deploy.go:584]: This was required as a part of an earlier change to the go-octopusdeploy project that hadn't been included in the CLI yet.

File: pkg/cmd/tenant/variables/update/update.go [hunk 2]
```diff
@@ -292,40 +293,40 @@ func PromptForVariable(opts *UpdateOptions, tenantVariables *variables.TenantVar
 	return selectedVariable, nil
 }
 
-func mapVariableControlTypeToVariableType(controlType variables.ControlType) (sharedVariable.VariableType, error) {
+func mapVariableControlTypeToVariableType(controlType resources.ControlType) (sharedVariable.VariableType, error) {
 	switch controlType {
-	case variables.ControlTypeSingleLineText, variables.ControlTypeMultiLineText:
+	case resources.ControlTypeSingleLineText, resources.ControlTypeMultiLineText:
```
Comment (IsaacCalligeros95) [inline pkg/cmd/tenant/variables/update/update.go:298]: The variable.ControlType* usage required in deployments created a circular reference, this has been moved to resources.

**Review by benPearce1 — APPROVED** [review]
LGTM
